-keep class yourpackage.** { *; }
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-verbose
-keep class com.appsflyer.** { *; }
-keepattributes Signature
-keepclassmembers class com.vula.vulkan.com.lcapp.** {*;}
-obfuscationdictionary dictionary.txt
-packageobfuscationdictionary dictionary.txt
-classobfuscationdictionary dictionary.txt
